# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: activity_tracker_development
  pool: 8
  username: root
  password: root
  # password: R00t@!23     # RC UAT
  socket: /var/run/mysqld/mysqld.sock
test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: activity_tracker_test
  pool: 8
  username: root
  password: root
  # password: R00t@!23     # RC UAT
  socket:  /var/run/mysqld/mysqld.sock
production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: activity_tracker_production
  pool: 8
  username: root
  password: root
  # password: R00t@!23     # RC UAT
  socket: /var/run/mysqld/mysqld.sock
