# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 64bce7721ff8dcd9bac9cec22f0fbf1a7fac29f40ebc67a2cee11796080d8aa1a5a306721b070c6ccf2825af3f32e35380f9c836ba6c5d834325e708615293cc

test:
  secret_key_base: 658acb52d6ae883ecb1e4804038d11655d8c1694e27a2dc8ebce076fc68c62511dec8dcd111a9eb64d33bcdceb07c15f42f3bd108c50e1ca23a5c461893dceda

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
